### ISSUE TITLE
issue with directory of the same name/architecture

### ISSUE THREAD

**Issue by DarkHeros09** [mikededo/dartBarrelFileGenerator#7]
Hi Mike

First of all thank you very much for this great extension, second there seems to be an issue when generating a barrel file for a specific folder with a name that also exist in the test directory.

```
- lib
   └ models
           └ model.dart
- test
   └ models
           └ model_test.dart
```

The generated file will also export the test directory imports.

can you please fix this issue.

**Comment by mikededo** [comment]
If I understand you, you choose to generate a barrel file in the `lib/models` folder, and it includes the `modules_test.dart` file, am I right? Does it happen when you choose to generate the barrel file for the current folder, or for the current folder and its subfolders? Or both?

**Comment by DarkHeros09** [comment]
no, when i generate a barrel file in the `lib/models` that contain 1,2 file, the generated file will contain exports of 1,2,3,4 files.
3,4 file are existed in the test directory with the same folder name `test/models`.

**Comment by mikededo** [comment]
Alright! :smile:

I will try to recreate the issue as soon as possible (currently I'm a bit busy)! However, feel free to clone and contribute to the extension 🥇

**Comment by DarkHeros09** [comment]
Alright thank you for your quick response, I wish that i could contribute to this great extension, but sadly my programing skills are only limited to flutter.
Anyway take your time, and have a good day.

**Comment by mikededo** [comment]
I will give you feedback as soon as possible

**Comment by mikededo** [comment]
Error was fix! Updating the extension asap!

**Comment by DarkHeros09** [comment]
Thank you very much.

**Comment by DarkHeros09** [comment]
Hi mike, i hope you are doing well.
i was wondering when do you planning to release the new update on the VSCode store?

**Comment by mikededo** [comment]
My most sincere apologies @DarkHeros09! For some reason I completely forgot to publish the update! It is being published as I answer you!

I am sorry 😅

**Comment by DarkHeros09** [comment]
> My most sincere apologies @DarkHeros09! For some reason I completely forgot to publish the update! It is being published as I answer you!
> 
> I am sorry 😅 

Great, happy to hear that.
Also nothing to apologize for, you are doing a great job.

**Comment by mikededo** [comment]
I would appreciate you gave me feedback of the extension, to check that the problem has been solved as you expected 😄

**Comment by DarkHeros09** [comment]
> 
> 
> I would appreciate you gave me feedback of the extension, to check that the problem has been solved as you expected 😄

sadly the problem still persist, i uninstall then installed the extension again just to make sure.😢

**Comment by mikededo** [comment]
Have you made sure the version you were using it is the 1.2.1?

**Comment by DarkHeros09** [comment]
Yes i did, i even deleted the extension manually from the hidden folder, then updated to `v1.2.1`.

**Comment by mikededo** [comment]
Yes, you are right, the issues it is not solved. I will revise everything as soon as I can.

**Comment by mikededo** [comment]
I've tried in Linux and it seems to work. What OS are you using @DarkHeros09?

**Comment by DarkHeros09** [comment]
Win10 v20H2.

**Comment by mikededo** [comment]
I will inspect on Windows, then

**Comment by mikededo** [comment]
Hello @DarkHeros09 😄! I'm currently really busy with work and uni. I've had no time no check why the error happens. As soon as I can I will try to solve it. Just give me a wekk!

**Comment by DarkHeros09** [comment]
Hi @mikededo 
Man don't you worry. take a month if you have, life is priorities, and uni is definitely number 1 here so take your time.

Good luck 👍.

**Comment by mikededo** [comment]
Hello @DarkHeros09!

The wait is over! 😄. I have published an update which solves the issues in Windows OS machines. I've been testing it out and it works as expected.

Thank you for your patience, feel free to contact me when needed! 💯
